### ISSUE TITLE
Hover on a row

### ISSUE THREAD

**Issue by 0xdavid7** [tctien342/react-simple-tailwind-table#1]
- When the mouse is entered on whatever owned by a row, this row will be hovered.
- Styles:
+ BackgroundColor
+ Scale
+ Font
+ Duration

**Comment by tctien342** [comment]
Implements `rowClassName` and `onClickRow?: (rowData: T, index: number) => void;` for handle complex style:

Hover can be trigger by using tailwind `group` feature
```ts
// TailwindComponent
rowClassName="group"

// Columns configuration
body: {
   className: "group-hover:!bg-gray-400 group-active:!bg-gray-100"
}
```

`useTableConfiguration` now has `defaultConfig` will apply into all columns, use it for faster col implements

see `index.stories.tsx` for more example
